apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: loganalyzers.mlops.dev
spec:
  group: mlops.dev
  scope: Namespaced
  names:
    plural: loganalyzers
    singular: loganalyzer
    kind: LogAnalyzer
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                podSelector:
                  type: object
                  additionalProperties: true
                llmProvider:
                  type: string
                  enum:
                    - openai
                    - gemini
                llmModel:
                  type: string
                prompt:
                  type: string
            status:
              type: object
              properties:
                analysis:
                  type: string
      subresources:
        status: {}
