apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "loganalyzer.fullname" . }}
rules:
- apiGroups: ["mlops.dev"]
  resources: ["loganalyzers","loganalyzers/status"]
  verbs: ["get","list","watch","update","patch"]
- apiGroups: [""]
  resources: ["pods","pods/log"]
  verbs: ["get","list","watch"]